POST http://localhost:8080/auth/login HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "password"
}


###

POST http://localhost:8080/auth/login HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "password"
}

###

POST http://localhost:8080/order/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiYWRtaW4iLCJpYXQiOjE3MDkyNTAyMTIsInJvbGVzIjoiQURNSU4ifQ.iVCFO3AcxZSGxX0-f5FQD2JXUoO-JW1AxPr6h8imftmM-zPnEa2heCgx04dcz9w4-G33r6qoO9MntKXAw9cbt7YqGa4eE59lMprf8dsSdYJPjjrxfn_jSGjbCx-1nfD1_GMjrzE0Ly8czE0peg543pfXOyI5Fp9jtL0nu5ZRkPail02_InB4ycUjXqiLiIkaD_qmramFkm3kxPu47ZwNFk_xwtNY_5_rnnztXTGw4GELZ_sfChu08bQtfxlMGn-nMJHtaRscel1VTDb8S32oBzYuA9Dt_gtggf4fuPWRCvUFp4aVeE9UMxCTIDXwsLDicptqD6xEyVI8HuMIXTTFww

{
        "dish_id": 33,
        "veggie": false,
        "date": "2024-03-01"
       
}

