POST http://localhost:8080/auth/login HTTP/1.1
content-type: application/json

{
    "username": "test",
    "password": "test"
}


###

POST http://localhost:8080/auth/login HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "password"
}

###

POST http://localhost:8080/admin/promote HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiYWRtaW4iLCJpYXQiOjE3MDc2MTk3MTAsInJvbGVzIjoiQURNSU4ifQ.EuaoqULAKIm2NsDkdMqyX-dYCh4q1YeRqeb1EjysCSfFT3pzgGOdsM20uXSdrJS7LCjIm9nhEa4LWb3O9rjC5qsyouzdIQ3J7qdhUYOytWe7WfggEXOGA4IHP41K9mtHvpoTvOWsXM2rlyL_7BNw_pk01n7i6sVB6Zqw9z8C2jLk1gQbZlBYFLj8gk6pWC-8KvRwYUhnu_bHJqz0D14LL0nzDQnyfo2JLJRdnc3mvG3JdhMvRR7EYIzaCE_cXqfLyB7Dxf3RkvKg2FDarbgPhhyaczLrCaG8Y8vuOY_1Ec55Qt55j0Yt3sRPJuNh4UBXV_5G7N9wFHNsujuBBN8IeA

{
    "username": "test"
}

