services:
  test-db:
    container_name: mysql-test
    platform: linux/amd64
    image: mysql:latest
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
      MYSQL_ROOT_PASSWORD: test_root_password
    ports:
      - "3307:3306"
    volumes:
      - test_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  test_db_data:
